# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"generate": "00_numpy.ipynb",
         "square_root_by_exhaustive": "01_python03.ipynb",
         "square_root_by_binary_search": "01_python03.ipynb",
         "square_root_by_newton": "01_python03.ipynb",
         "search": "01_python03.ipynb",
         "select_sort": "01_python03.ipynb"}

modules = ["numpycore.py",
           "py03.py"]

doc_url = "https://greyhawk.github.io/pandas_exercises/"

git_url = "https://github.com/greyhawk/pandas_exercises/tree/master/"

def custom_doc_links(name): return None
