# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"generate": "00_numpy.ipynb"}

modules = ["numpycore.py"]

doc_url = "https://greyhawk.github.io/pandas_exercises/"

git_url = "https://github.com/greyhawk/pandas_exercises/tree/master/"

def custom_doc_links(name): return None
