# AUTOGENERATED! DO NOT EDIT! File to edit: 00_numpy.ipynb (unless otherwise specified).

__all__ = ['generate']

# Cell
import numpy as np

# Cell
def generate():
    for x in range(10):
        yield x